-- Create product_variants table for true variant-based product options
-- Each row represents a unique combination of size + color + shape with its own image
-- The existing sizes/colors/shapes/has_options columns on products table are kept for backward compatibility

CREATE TABLE IF NOT EXISTS product_variants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  size TEXT NOT NULL DEFAULT '',
  color TEXT NOT NULL DEFAULT '',
  shape TEXT NOT NULL DEFAULT '',
  image TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Unique constraint: prevent duplicate variants with same product_id + size + color + shape
CREATE UNIQUE INDEX IF NOT EXISTS idx_product_variants_unique 
  ON product_variants(product_id, size, color, shape);

-- Index for fast lookups by product
CREATE INDEX IF NOT EXISTS idx_product_variants_product_id 
  ON product_variants(product_id);

-- Enable Row Level Security
ALTER TABLE product_variants ENABLE ROW LEVEL SECURITY;

-- Public read access (anyone can view product variants)
CREATE POLICY "Public can view product variants" ON product_variants
  FOR SELECT
  USING (true);

-- Authenticated admins can insert product variants
CREATE POLICY "Admins can insert product variants" ON product_variants
  FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

-- Authenticated admins can update product variants
CREATE POLICY "Admins can update product variants" ON product_variants
  FOR UPDATE
  USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- Authenticated admins can delete product variants
CREATE POLICY "Admins can delete product variants" ON product_variants
  FOR DELETE
  USING (auth.role() = 'authenticated');

