-- ============================
-- Paddle Depot: Admin Allowlist
-- ============================
-- This migration implements a secure admin-only authorization system.
-- 
-- How it works:
-- 1. An `admin_allowlist` table stores the emails of designated admin users.
-- 2. A reusable `is_admin()` SQL function checks if the currently authenticated
--    user's email exists in the allowlist.
-- 3. All RLS policies on `products` and `storage.objects` use `is_admin()`
--    instead of `auth.role() = 'authenticated'`.
-- 4. This means only users whose email is in the allowlist can INSERT, UPDATE,
--    DELETE products or upload images to storage.
-- 5. Public users can still SELECT products and view images.
-- 6. Non-admin authenticated users (e.g., users who signed up but aren't in the
--    allowlist) are blocked at the database level.

-- ============================================================
-- STEP 1: Create the admin_allowlist table
-- ============================================================
CREATE TABLE IF NOT EXISTS admin_allowlist (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  added_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- STEP 2: Enable RLS on the allowlist table itself
-- (Only admins can read the allowlist)
-- ============================================================
ALTER TABLE admin_allowlist ENABLE ROW LEVEL SECURITY;

-- Admins can see the allowlist (needed for frontend checks)
CREATE POLICY "Admins can view allowlist" ON admin_allowlist
  FOR SELECT
  USING (auth.jwt() ->> 'email' IN (SELECT email FROM admin_allowlist));

-- Only the database owner (via Supabase dashboard) can insert/update/delete
-- from the allowlist, so we don't create INSERT/UPDATE/DELETE policies.
-- This prevents any authenticated user from adding themselves as admin.

-- ============================================================
-- STEP 3: Create a reusable is_admin() function
-- ============================================================
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM admin_allowlist
    WHERE email = auth.jwt() ->> 'email'
  );
$$;

-- ============================================================
-- STEP 4: Drop OLD policies that used auth.role() = 'authenticated'
-- ============================================================
DROP POLICY IF EXISTS "Admins can insert products" ON products;
DROP POLICY IF EXISTS "Admins can update products" ON products;
DROP POLICY IF EXISTS "Admins can delete products" ON products;
DROP POLICY IF EXISTS "Admins can upload paddle images" ON storage.objects;

-- ============================================================
-- STEP 5: Create NEW admin-only policies for products table
-- ============================================================
-- Public read access (unchanged - anyone can view products)
-- "Public can view products" already exists and uses USING (true)

-- Admin-only insert
CREATE POLICY "Admins can insert products" ON products
  FOR INSERT
  WITH CHECK (public.is_admin());

-- Admin-only update
CREATE POLICY "Admins can update products" ON products
  FOR UPDATE
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

-- Admin-only delete
CREATE POLICY "Admins can delete products" ON products
  FOR DELETE
  USING (public.is_admin());

-- ============================================================
-- STEP 6: Create NEW admin-only policy for storage objects
-- ============================================================
-- Public can view paddle images (unchanged)
-- "Public can view paddle images" already exists and uses USING (bucket_id = 'paddles')

-- Admin-only upload
DROP POLICY IF EXISTS "Admins can upload paddle images" ON storage.objects;
CREATE POLICY "Admins can upload paddle images" ON storage.objects
  FOR INSERT
  WITH CHECK (bucket_id = 'paddles' AND public.is_admin());

-- Admin-only update on storage objects (needed for replacing images)
CREATE POLICY "Admins can update paddle images" ON storage.objects
  FOR UPDATE
  USING (bucket_id = 'paddles' AND public.is_admin())
  WITH CHECK (bucket_id = 'paddles' AND public.is_admin());

-- Admin-only delete on storage objects
CREATE POLICY "Admins can delete paddle images" ON storage.objects
  FOR DELETE
  USING (bucket_id = 'paddles' AND public.is_admin());

-- ============================================================
-- STEP 7: Insert your designated admin email(s) below
-- ============================================================
-- IMPORTANT: Replace 'admin@yourdomain.com' with YOUR actual admin email
-- You can add multiple admins by inserting additional rows.
--
-- Example:
--   INSERT INTO admin_allowlist (email) VALUES ('christian@example.com');
--   INSERT INTO admin_allowlist (email) VALUES ('another-admin@example.com');
--
-- You can run these INSERT statements in the Supabase SQL Editor
-- OR uncomment the line below and replace with your email BEFORE running
-- this migration in the Supabase dashboard.

-- INSERT INTO admin_allowlist (email) VALUES ('admin@yourdomain.com');

