-- ============================
-- Paddle Depot: Admin Activity Log
-- ============================
-- This migration creates an admin_log table to track real admin actions.
--
-- Logged action types:
--   product_created
--   product_updated
--   product_deleted
--   product_duplicated
--   stock_status_changed
--   featured_changed
--   is_new_changed
--   image_uploaded
--   image_replaced
--   image_removed
--   price_changed
--
-- RLS: Only admins (via is_admin()) can INSERT and SELECT logs.
-- Public users have no access.

-- ============================================================
-- STEP 1: Create the admin_log table
-- ============================================================
CREATE TABLE IF NOT EXISTS admin_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  product_id BIGINT,
  product_name TEXT,
  admin_email TEXT NOT NULL DEFAULT '',
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for faster queries
CREATE INDEX IF NOT EXISTS idx_admin_log_created_at ON admin_log (created_at DESC);

-- ============================================================
-- STEP 2: Enable RLS
-- ============================================================
ALTER TABLE admin_log ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- STEP 3: RLS policies
-- ============================================================

-- Only admins can view activity logs
CREATE POLICY "Admins can view admin_log" ON admin_log
  FOR SELECT
  USING (public.is_admin());

-- Only admins can insert activity logs
CREATE POLICY "Admins can insert admin_log" ON admin_log
  FOR INSERT
  WITH CHECK (public.is_admin());

-- No UPDATE or DELETE policies — logs are append-only for accountability

