-- Create products table
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  brand TEXT NOT NULL,
  price NUMERIC NOT NULL,
  image TEXT NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  stock_status TEXT NOT NULL DEFAULT 'In Stock' CHECK (stock_status IN ('In Stock', 'Low Stock', 'Pre-Order', 'Out of Stock')),
  featured BOOLEAN NOT NULL DEFAULT false,
  is_new BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

-- Public read access (anyone can view products)
CREATE POLICY "Public can view products" ON products
  FOR SELECT
  USING (true);

-- Authenticated admins can insert products
CREATE POLICY "Admins can insert products" ON products
  FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

-- Authenticated admins can update products
CREATE POLICY "Admins can update products" ON products
  FOR UPDATE
  USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- Authenticated admins can delete products
CREATE POLICY "Admins can delete products" ON products
  FOR DELETE
  USING (auth.role() = 'authenticated');

-- Create a bucket for paddle images
INSERT INTO storage.buckets (id, name, public) VALUES ('paddles', 'paddles', true)
ON CONFLICT (id) DO NOTHING;

-- Public can view paddle images
CREATE POLICY "Public can view paddle images" ON storage.objects
  FOR SELECT
  USING (bucket_id = 'paddles');

-- Authenticated admins can upload paddle images
CREATE POLICY "Admins can upload paddle images" ON storage.objects
  FOR INSERT
  WITH CHECK (bucket_id = 'paddles' AND auth.role() = 'authenticated');

